"""
==================================================
ForgePy
Readme Template
==================================================
"""


def get_readme(project_name: str) -> str:
    return f"""# {project_name}

Generated by ForgePy.

Version: 0.1
"""